### PR TITLE
password hashing

### PR DESCRIPTION
**Pull request by anubhabsen**
This is incorrect and doesn't work

### CODE REVIEW

**Comment by meghprkh** [comment]
When you install `bcrypt`, add it to `package.json`, so that when others do `npm install` they too will get brcrypt. Please run `npm install brcypt --save` to do this

**Comment by anubhabsen** [comment]
The auth isn't functioning either I believe.

**Comment by meghprkh** [comment]
You also need to edit create sample models and store the hash of the password there. (add saltRounds to config so that reuse and after sync works, try async)

``` js

      { email: 'megh@gmail.com', password: bcrypt.hashSync('password', 10), name: 'Megh'},
      { email: 'megh2@gmail.com', password: bcrypt.hashSync('password', 10), name: 'Megh2'}
```

**Comment by anubhabsen** [comment]
Some building npm failed it seems, also auth still doesn't work

**Comment by meghprkh** [comment]
login worked for me. try deleting the db

**Comment by meghprkh** [comment]
dunno why travis is failing though

**Comment by anubhabsen** [comment]
Clearing database worked. Now async?

**Comment by meghprkh** [comment]
Closed in favor of #16

**Pull request closed without merging**
